In [1]:
import pandas as pd

In [2]:
tabela = pd.read_csv('transferencias.csv') # Carregar tabela do arquivo
tabela # Visualização

,numero_conta_pagadora,agencia_conta_pagadora,numero_conta_recebedora,agencia_conta_recebedora,valor,método,data
0,12345-1,1,23456-2,2,5967.93,TED,08/04/2025
1,12345-1,1,34567-3,3,3952.04,TED,07/04/2025
2,12345-1,1,45678-4,4,3135.54,PIX,07/04/2025
3,12345-1,1,56789-5,5,5383.63,Débito,07/04/2025
4,23456-2,2,12345-1,1,5460.89,PIX,07/04/2025
5,23456-2,2,34567-3,3,5063.76,Débito,08/04/2025
6,23456-2,2,45678-4,4,3710.04,TED,08/04/2025
7,23456-2,2,56789-5,5,7449.19,TED,08/04/2025
8,34567-3,3,12345-1,1,3774.83,PIX,07/04/2025
9,34567-3,3,23456-2,2,5845.80,TED,08/04/2025
10,34567-3,3,45678-4,4,2708.04,PIX,08/04/2025
11,34567-3,3,56789-5,5,5985.90,Débito,07/04/2025
12,45678-4,4,12345-1,1,6515.96,Débito,08/04/2025
13,45678-4,4,23456-2,2,8013.86,Débito,08/04/2025
14,45678-4,4,34567-3,3,6314.87,TED,07/04/2025
15,45678-4,4,56789-5,5,7898.09,Débito,08/04/2025
16,56789-5,5,12345-1,1,6905.20,PIX,08/04/2025
17,56789-5,5,23456-2,2,9645.54,TED,08/04/2025
18,56789-5,5,34567-3,3,6175.94,PIX,07/04/2025
19,56789-5,5,45678-4,4,4842.65,TED,08/04/2025

## Exercício 1
Verifique quantas contas bancárias existem na tabela

In [45]:
[tabela['numero_conta_pagadora'].unique(), tabela['numero_conta_recebedora'].unique()]

[array(['12345-1', '23456-2', '34567-3', '45678-4', '56789-5'],
       dtype=object),
 array(['23456-2', '34567-3', '45678-4', '56789-5', '12345-1'],
       dtype=object)]

## Exercício 2
Liste os números e agências de todas as contas bancárias

In [40]:
tabela[["numero_conta_pagadora", "agencia_conta_pagadora"]].drop_duplicates()

   numero_conta_pagadora  agencia_conta_pagadora
0                12345-1                       1
4                23456-2                       2
8                34567-3                       3
12               45678-4                       4
16               56789-5                       5

## Exercício 3
Liste os métodos de transferência existentes na tabela

In [ ]:
tabela["método"].unique()

[array(['TED', 'PIX', 'Débito'], dtype=object)]

## Exercício 4
Liste as datas existentes na tabela

In [49]:
tabela["data"].unique()

array(['08/04/2025', '07/04/2025'], dtype=object)

## Exercício 5
Para cada conta, calcule a média (método mean) e o desvio padrão (método std) dos valores transferidos

In [ ]:
for conta in tabela["numero_conta_pagadora"].unique():
    print(f"Conta: {conta}")
    print(f"Media: {tabela[tabela['numero_conta_pagadora'] == conta]['valor'].mean()}")
    print(f"Desvio: {tabela[tabela['numero_conta_pagadora'] == conta]['valor'].std()} \n")

Conta: 23456-2
Media: 7368.2825
Desvio: 1814.90239561939

Conta: 34567-3
Media: 5376.652499999999
Desvio: 1102.5024681264888

Conta: 45678-4
Media: 3599.0674999999997
Desvio: 925.1306356536896

Conta: 56789-5
Media: 6679.2025
Desvio: 1188.5206416767303

Conta: 12345-1
Media: 5664.22
Desvio: 1399.5987578588372

## Exercício 6
Para cada conta, calcule a média (método mean) e o desvio padrão (método std) dos valores recebidos

In [55]:
for conta in tabela["numero_conta_recebedora"].unique():
    print(f"Conta: {conta}")
    print(f"Media: {tabela[tabela['numero_conta_recebedora'] == conta]['valor'].mean()}")
    print(f"Desvio: {tabela[tabela['numero_conta_recebedora'] == conta]['valor'].std()} \n")

Conta: 23456-2
Media: 7368.2825
Desvio: 1814.90239561939

Conta: 34567-3
Media: 5376.652499999999
Desvio: 1102.5024681264888

Conta: 45678-4
Media: 3599.0674999999997
Desvio: 925.1306356536896

Conta: 56789-5
Media: 6679.2025
Desvio: 1188.5206416767303

Conta: 12345-1
Media: 5664.22
Desvio: 1399.5987578588372

## Exercício 7
Calcule a quantidade e o percentual de ocorrências de cada método de transferência

In [56]:
tabela["método"].value_counts()

método
TED       8
PIX       6
Débito    6
Name: count, dtype: int64

## Exercício 8
Calcule a quantidade de transferências realizadas em cada dia

In [58]:
for data, metodo in tabela.groupby(["data", "método"]):
    print(f"Data: {data} - Método: {metodo['método'].unique()[0]} - Total: {metodo['valor'].sum()}") # Método de pagamento

Data: ('07/04/2025', 'Débito') - Método: Débito - Total: 11369.529999999999
Data: ('07/04/2025', 'PIX') - Método: PIX - Total: 18547.2
Data: ('07/04/2025', 'TED') - Método: TED - Total: 10266.91
Data: ('08/04/2025', 'Débito') - Método: Débito - Total: 27491.670000000002
Data: ('08/04/2025', 'PIX') - Método: PIX - Total: 9613.24
Data: ('08/04/2025', 'TED') - Método: TED - Total: 37461.15

## Exercício 9
Calcule o total recebido por cada conta

## Exercício 10
Calcule o total pago por cada conta

## Exercício 11
Calcule a quantidade de dinheiro transferido com cada método de transferência

## Exercício 12
Calcule a quantidade total de dinheiro transferido na tabela

## Exercício 13
Calcule quantos porcento desse total de dinheiro transferido foi transferido com cada método