# Aula de Pandas

**Prof. Filipe Chagas Ferraz**

Pandas é o principal pacote Python de manipulação de dados estruturados. Nesta aula, vamos ver algumas funcionalidades básicas do Pandas.

## Importação

Pandas é uma biblioteca que normalmente precisa ser instalada com o comando ``pip install pandas``. No Google Colab, o pandas já é instalado por padrão, então só precisamos importar.

Por convenção, utiliza-se o apelido 'pd' na importação do pandas.

In [1]:
import pandas as pd

## DataFrames

No Pandas, uma tabela é um DataFrame.

Podemos criar DataFrames a partir de listas ou dicionários, das seguintes formas:

In [ ]:
# Criando dataframe a partir de listas
df = pd.DataFrame(
    data=[
        ['Fulano', 20],
        ['Ciclano', 30],
        ['Beltrano', 40]
    ],
    columns=['Nome', 'Idade']
)

df # Para visualizar o dataframe no notebook

       Nome  Idade
0    Fulano     20
1   Ciclano     30
2  Beltrano     40

In [ ]:
# Criando dataframe a partir de dicionário de colunas
df = pd.DataFrame(
    data={
        'Nome': ['Fulano', 'Ciclano', 'Beltrano'],
        'Idade': [20, 30, 40]
    }
)

df # Para visualizar o dataframe no notebook

       Nome  Idade
0    Fulano     20
1   Ciclano     30
2  Beltrano     40

In [ ]:
# Criando dataframe a partir de lista de dicionários
df = pd.DataFrame(
    data=[
        {'Nome': 'Fulano', 'Idade': 20},
        {'Nome': 'Ciclano', 'Idade': 30},
        {'Nome': 'Beltrano', 'Idade': 40}
    ]
)

df # Para visualizar o dataframe

       Nome  Idade
0    Fulano     20
1   Ciclano     30
2  Beltrano     40

Também podemos importar dados de arquivos CSV e planilhas do Excel. Nesta aula, utilizamos o arquivo ``historico_escolar.csv``. Certifique-se de ter carregado ele nos arquivos da sessão do Colab.

In [2]:
df = pd.read_csv('historico_escolar.csv') # Importação dos dados do arquivo
df # Para visualizar o dataframe

,id_aluno,nome_aluno,turma,trimestre,data,ano_letivo,disciplina,nota,faltas
0,08f39f2a,Sofia,1,1,2025-03-15,1,Matemática,2.48,0.31
1,08f39f2a,Sofia,1,1,2025-03-21,1,Física,4.78,0.13
2,08f39f2a,Sofia,1,1,2025-03-22,1,Química,6.76,0.35
3,08f39f2a,Sofia,1,1,2025-03-25,1,Biologia,5.49,0.29
4,08f39f2a,Sofia,1,1,2025-03-05,1,Português,7.63,0.77
...,...,...,...,...,...,...,...,...,...
2695,6bd6e02d,Fernanda,3,3,2025-09-16,3,História,1.60,0.48
2696,6bd6e02d,Fernanda,3,3,2025-09-21,3,Geografia,5.49,0.08
2697,6bd6e02d,Fernanda,3,3,2025-09-02,3,Filosofia,8.32,0.43
2698,6bd6e02d,Fernanda,3,3,2025-09-04,3,Sociologia,2.13,0.63
2699,6bd6e02d,Fernanda,3,3,2025-09-23,3,Inglês,3.50,0.34

Nesta tabela, temos todas as notas trimestrais dos alunos do ensino médio de uma escola. Há uma nota para cada aluno, de cada turma, em cada trimestre e cada disciplina. Há também os índices de falta (índice 0 é 0%, índice 0.5 é 50% e índice 1 é 100%).

Para obter os valores de um coluna específica, ou um grupo de colunas, fazemos o seguinte:

In [ ]:
df['nome_aluno'] # Obter apenas a coluna de nomes

0          Sofia
1          Sofia
2          Sofia
3          Sofia
4          Sofia
          ...
2695    Fernanda
2696    Fernanda
2697    Fernanda
2698    Fernanda
2699    Fernanda
Name: nome_aluno, Length: 2700, dtype: object

In [ ]:
df[['id_aluno', 'nome_aluno']] # Obter as colunas de nome e id

      id_aluno nome_aluno
0     08f39f2a      Sofia
1     08f39f2a      Sofia
2     08f39f2a      Sofia
3     08f39f2a      Sofia
4     08f39f2a      Sofia
...        ...        ...
2695  6bd6e02d   Fernanda
2696  6bd6e02d   Fernanda
2697  6bd6e02d   Fernanda
2698  6bd6e02d   Fernanda
2699  6bd6e02d   Fernanda

[2700 rows x 2 columns]

Podemos usar o método Unique para obter o conjunto de valores observados em uma coluna, sem repetições.

In [ ]:
df['id_aluno'].unique() # Obter id únicos

array(['08f39f2a', '806b0639', 'd8fd00ea', 'de338a20', 'c15f5475',
       '67cb42f7', 'c91b3310', '6cd82f6e', '34204d34', '58a5aa68',
       '1c46e900', 'e98a2801', 'f4f38cd7', '737830fb', 'f83dced7',
       '592bca95', 'a9406c0b', '4fea5426', '61218fea', '4ec942b1',
       '1612844d', '588efc58', '28251505', '84a7b9e4', '058d8375',
       'd3cb7833', 'b8d9a93d', '136e881b', '8a0b02b6', 'ba4efb1a',
       'a17b0504', '45193fe8', '735da18e', '4b0b4143', '05db83c4',
       'e18dea18', '2a56d990', '85b6c642', '83fe64ec', '1a95356d',
       '2678384b', '7ba612ba', 'e15e9f77', '2d7c7e0a', '09d257de',
       '5f05a6ec', '8cb8a910', 'efbcb57b', '46df783b', '1bbd109d',
       'dafec5fa', '9559ad27', '19ab8710', 'ab4bf4aa', '92996e5f',
       '30ab33b6', 'a761e3cf', '88add043', 'fbce3049', '18e97af1',
       '09d7896b', 'ed0e9001', '69fad168', '0abea6d1', '818cea73',
       'b106034d', 'd3675b98', 'e1e87605', '6738c8a3', 'eaee4b52',
       '7ea945a8', '1c69499b', '0e5f2a4e', '8a347324', 'ab62851f',
       '54afb328', 'c4d1d752', 'fa478217', '20516a1a', 'f30c1e4d',
       'f287c2cb', '7675856f', '608e86bd', '64899ff0', '752023c9',
       '7018c144', 'e4adf10e', '4952909b', '8b73164c', '6bd6e02d'],
      dtype=object)

In [9]:
# Mostrar valores com for
for id_aluno in df['id_aluno'].unique(): # Para cada id único
    print(id_aluno) # Imprimir id

08f39f2a
806b0639
d8fd00ea
de338a20
c15f5475
67cb42f7
c91b3310
6cd82f6e
34204d34
58a5aa68
1c46e900
e98a2801
f4f38cd7
737830fb
f83dced7
592bca95
a9406c0b
4fea5426
61218fea
4ec942b1
1612844d
588efc58
28251505
84a7b9e4
058d8375
d3cb7833
b8d9a93d
136e881b
8a0b02b6
ba4efb1a
a17b0504
45193fe8
735da18e
4b0b4143
05db83c4
e18dea18
2a56d990
85b6c642
83fe64ec
1a95356d
2678384b
7ba612ba
e15e9f77
2d7c7e0a
09d257de
5f05a6ec
8cb8a910
efbcb57b
46df783b
1bbd109d
dafec5fa
9559ad27
19ab8710
ab4bf4aa
92996e5f
30ab33b6
a761e3cf
88add043
fbce3049
18e97af1
09d7896b
ed0e9001
69fad168
0abea6d1
818cea73
b106034d
d3675b98
e1e87605
6738c8a3
eaee4b52
7ea945a8
1c69499b
0e5f2a4e
8a347324
ab62851f
54afb328
c4d1d752
fa478217
20516a1a
f30c1e4d
f287c2cb
7675856f
608e86bd
64899ff0
752023c9
7018c144
e4adf10e
4952909b
8b73164c
6bd6e02d

Para obter dados de uma única linha a partir do índice dela, usamos iloc

In [ ]:
df.iloc[10] # Obtém 11ª linha

id_aluno        08f39f2a
nome_aluno         Sofia
turma                  1
trimestre              2
data          2025-06-19
ano_letivo             1
disciplina    Matemática
nota                3.77
faltas              0.82
Name: 10, dtype: object

Para obter uma linha e uma coluna, usamos loc

In [ ]:
df.loc[10, 'id_aluno'] # id_aluno da 11ª linha

'08f39f2a'

Vamos fazer, no Pandas, o equivalente a uma consulta SQL ``SELECT * FROM historico_escolar WHERE disciplina='História'``, para obter somente as notas de história.

In [5]:
df_historia = df[df['disciplina'] == 'História'] # Consulta SQL
df_historia # Visualizar dataframe

,id_aluno,nome_aluno,turma,trimestre,data,ano_letivo,disciplina,nota,faltas
5,08f39f2a,Sofia,1,1,2025-03-21,1,História,4.48,0.91
15,08f39f2a,Sofia,1,2,2025-06-19,1,História,3.47,0.97
25,08f39f2a,Sofia,1,3,2025-09-14,1,História,0.29,0.49
35,806b0639,Vanessa,1,1,2025-03-08,1,História,4.05,0.76
45,806b0639,Vanessa,1,2,2025-06-14,1,História,2.22,0.54
...,...,...,...,...,...,...,...,...,...
2655,8b73164c,Sofia,3,2,2025-06-21,3,História,5.31,0.61
2665,8b73164c,Sofia,3,3,2025-09-24,3,História,4.02,0.73
2675,6bd6e02d,Fernanda,3,1,2025-03-01,3,História,2.36,0.03
2685,6bd6e02d,Fernanda,3,2,2025-06-15,3,História,8.58,0.77
2695,6bd6e02d,Fernanda,3,3,2025-09-16,3,História,1.60,0.48

Agora vamos obter as notas de história do 1º ano.

Isso aquivale à consulta ``SELECT * FROM historico_escolar WHERE disciplina='História' AND ano_letivo=1``.

In [ ]:
df_historia_1ano = df[(df['disciplina'] == 'História') & (df['ano_letivo'] == 1)] # Consulta SQL
df_historia_1ano # Visualizar dataframe

,id_aluno,nome_aluno,turma,trimestre,data,ano_letivo,disciplina,nota,faltas
5,08f39f2a,Sofia,1,1,2025-03-21,1,História,4.48,0.91
15,08f39f2a,Sofia,1,2,2025-06-19,1,História,3.47,0.97
25,08f39f2a,Sofia,1,3,2025-09-14,1,História,0.29,0.49
35,806b0639,Vanessa,1,1,2025-03-08,1,História,4.05,0.76
45,806b0639,Vanessa,1,2,2025-06-14,1,História,2.22,0.54
...,...,...,...,...,...,...,...,...,...
855,8a0b02b6,Carlos,3,2,2025-06-05,1,História,7.64,0.35
865,8a0b02b6,Carlos,3,3,2025-09-23,1,História,6.28,0.97
875,ba4efb1a,Larissa,3,1,2025-03-24,1,História,8.35,0.30
885,ba4efb1a,Larissa,3,2,2025-06-11,1,História,1.47,0.34
895,ba4efb1a,Larissa,3,3,2025-09-04,1,História,6.35,0.80

Assim como no SQL, no Pandas podemos utilizar agregadores para fazer cálculos como média e mediana.

In [ ]:
# Médias
nota_media_geral = df['nota'].mean() # Média de notas
ifalta_medio_geral = df['faltas'].mean() # Média de índices de falta
print(f'Média geral de notas: {nota_media_geral}\nIndice de faltas médio geral: {ifalta_medio_geral*100}%')

# Mediana
nota_mediana_geral = df['nota'].median() # Mediana de notas
faltas_mediana_geral = df['faltas'].median() # Mediana de índices de falta
print(f'Mediana geral de notas: {nota_mediana_geral}\nIndice de faltas médio geral: {faltas_mediana_geral*100}%')

Média geral de notas: 5.0702
Indice de faltas médio geral: 50.3737037037037%
Mediana geral de notas: 5.06
Indice de faltas médio geral: 50.0%

Agora, vamos criar uma tabela para visualizar as médias de notas de cada disciplina.

Em SQL, isso seria feito com uma consulta ``SELECT disciplina, AVG(nota) FROM historico_escolar GROUP BY disciplina``.

In [ ]:
nota_media_por_disciplina = df.groupby('disciplina')['nota'].mean()
nota_media_por_disciplina # Visualizar dataframe

disciplina
Biologia      4.996296
Filosofia     5.012519
Física        4.964593
Geografia     4.996333
História      5.242630
Inglês        5.148778
Matemática    4.870000
Português     5.029963
Química       5.240407
Sociologia    5.200481
Name: nota, dtype: float64

Podemos fazer o group by por vários atributos, e aplicar a agregação a vários atributos também. No seguinte exemplo, criamos uma tabela de médias de notas e índices de falta por disciplina, ano letivo e turma.

In [ ]:
tabela_medias = df.groupby(['ano_letivo', 'turma', 'disciplina'])[['nota', 'faltas']].mean()
tabela_medias

                                 nota    faltas
ano_letivo turma disciplina
1          1     Biologia    4.724667  0.568667
                 Filosofia   4.693667  0.477333
                 Física      5.920667  0.564000
                 Geografia   5.921000  0.438333
                 História    4.486333  0.550000
...                               ...       ...
3          3     Inglês      6.632667  0.485333
                 Matemática  5.317333  0.436000
                 Português   5.369333  0.512000
                 Química     5.487000  0.483667
                 Sociologia  4.884333  0.537667

[90 rows x 2 columns]

Nesta tabela criada pelo groupby, os atributos de referência do agrupamento (ano_letivo, turma e disciplina) viram os índices da tabela (ou seja, seus valores são usados para indexar as linhas). Então, para obter uma linha específica dessa tabela, usamos loc especificando o ano letivo, a turma e a disciplina. Veja:

In [ ]:
tabela_medias.loc[(2, 1, 'Física')] # 2º ano, turma 1, Física

nota      4.186667
faltas    0.573667
Name: (2, 1, Física), dtype: float64

Podemos aplicar expressões aos valores de uma tabela. Nos seguintes exemplos, criamos colunas de aprovação por nota e aprovação por presença.

In [ ]:
aprovado_por_nota = df['nota'] >= 5.0 # A nota por trimestre e disciplina deve ser igual ou superior a 5
aprovado_por_nota

0       False
1       False
2        True
3        True
4        True
        ...
2695    False
2696     True
2697     True
2698    False
2699    False
Name: nota, Length: 2700, dtype: bool

In [ ]:
aprovado_por_freq = df['faltas'] <= 0.5 # Faltas devem ser menos de 50% por trimestre e disciplina
aprovado_por_freq

0       False
1        True
2       False
3       False
4       False
        ...
2695    False
2696     True
2697    False
2698    False
2699    False
Name: faltas, Length: 2700, dtype: bool

In [ ]:
aprovado = aprovado_por_nota & aprovado_por_freq # Aplicando a condição de aprovação
aprovado

0       False
1       False
2       False
3       False
4       False
        ...
2695    False
2696     True
2697    False
2698    False
2699    False
Length: 2700, dtype: bool

Podemos inserir essa coluna de reprovação na tabela, da seguinte forma:

In [ ]:
df['aprovado'] = aprovado # Criando coluna de aprovação
df

,id_aluno,nome_aluno,turma,trimestre,data,ano_letivo,disciplina,nota,faltas,aprovado
0,08f39f2a,Sofia,1,1,2025-03-15,1,Matemática,2.48,0.31,False
1,08f39f2a,Sofia,1,1,2025-03-21,1,Física,4.78,0.13,False
2,08f39f2a,Sofia,1,1,2025-03-22,1,Química,6.76,0.35,False
3,08f39f2a,Sofia,1,1,2025-03-25,1,Biologia,5.49,0.29,False
4,08f39f2a,Sofia,1,1,2025-03-05,1,Português,7.63,0.77,False
...,...,...,...,...,...,...,...,...,...,...
2695,6bd6e02d,Fernanda,3,3,2025-09-16,3,História,1.60,0.48,False
2696,6bd6e02d,Fernanda,3,3,2025-09-21,3,Geografia,5.49,0.08,True
2697,6bd6e02d,Fernanda,3,3,2025-09-02,3,Filosofia,8.32,0.43,False
2698,6bd6e02d,Fernanda,3,3,2025-09-04,3,Sociologia,2.13,0.63,False
2699,6bd6e02d,Fernanda,3,3,2025-09-23,3,Inglês,3.50,0.34,False

Agora, vamos obter apenas os alunos aprovados

In [ ]:
df[df['aprovado'] == True]

,id_aluno,nome_aluno,turma,trimestre,data,ano_letivo,disciplina,nota,faltas,aprovado
12,08f39f2a,Sofia,1,2,2025-06-16,1,Química,6.41,0.10,True
18,08f39f2a,Sofia,1,2,2025-06-05,1,Sociologia,5.25,0.10,True
38,806b0639,Vanessa,1,1,2025-03-16,1,Sociologia,6.23,0.20,True
46,806b0639,Vanessa,1,2,2025-06-14,1,Geografia,5.06,0.25,True
52,806b0639,Vanessa,1,3,2025-09-13,1,Química,7.27,0.09,True
...,...,...,...,...,...,...,...,...,...,...
2642,8b73164c,Sofia,3,1,2025-03-16,3,Química,5.79,0.09,True
2658,8b73164c,Sofia,3,2,2025-06-16,3,Sociologia,6.95,0.00,True
2659,8b73164c,Sofia,3,2,2025-06-26,3,Inglês,5.51,0.21,True
2682,6bd6e02d,Fernanda,3,2,2025-06-08,3,Química,9.35,0.14,True
2696,6bd6e02d,Fernanda,3,3,2025-09-21,3,Geografia,5.49,0.08,True

## Atividade

* Calcule o índice médio de aprovações por disciplina e ano letivo
* Para cada turma, ano letivo e disciplina, obtenha os alunos cuja nota está abaixo da média da turma na disciplina e no ano letivo.
* Para cada ano letivo, verifique qual é a disciplina em que os alunos mais têm reprovações
* Para cada ano letivo, verifique qual é a disciplina com mais aprovações
* Para cada ano letivo, verifique qual é a disciplina em que os alunos mais faltam
* Para cada ano letivo, verifique qual é a disciplina em que os alunos menos faltam